// Code generated by MockGen. DO NOT EDIT.
// Source: clab/dependency_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/srl-labs/containerlab/types"
)

// MockDependencyManager is a mock of DependencyManager interface.
type MockDependencyManager struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyManagerMockRecorder
}

// MockDependencyManagerMockRecorder is the mock recorder for MockDependencyManager.
type MockDependencyManagerMockRecorder struct {
	mock *MockDependencyManager
}

// NewMockDependencyManager creates a new mock instance.
func NewMockDependencyManager(ctrl *gomock.Controller) *MockDependencyManager {
	mock := &MockDependencyManager{ctrl: ctrl}
	mock.recorder = &MockDependencyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyManager) EXPECT() *MockDependencyManagerMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockDependencyManager) AddDependency(depender string, wf *types.WaitFor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDependency", depender, wf)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockDependencyManagerMockRecorder) AddDependency(depender, wf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockDependencyManager)(nil).AddDependency), depender, wf)
}

// AddNode mocks base method.
func (m *MockDependencyManager) AddNode(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNode", name)
}

// AddNode indicates an expected call of AddNode.
func (mr *MockDependencyManagerMockRecorder) AddNode(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNode", reflect.TypeOf((*MockDependencyManager)(nil).AddNode), name)
}

// CheckAcyclicity mocks base method.
func (m *MockDependencyManager) CheckAcyclicity() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAcyclicity")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAcyclicity indicates an expected call of CheckAcyclicity.
func (mr *MockDependencyManagerMockRecorder) CheckAcyclicity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAcyclicity", reflect.TypeOf((*MockDependencyManager)(nil).CheckAcyclicity))
}

// IsHealthCheckRequired mocks base method.
func (m *MockDependencyManager) IsHealthCheckRequired(nodeName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthCheckRequired", nodeName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsHealthCheckRequired indicates an expected call of IsHealthCheckRequired.
func (mr *MockDependencyManagerMockRecorder) IsHealthCheckRequired(nodeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthCheckRequired", reflect.TypeOf((*MockDependencyManager)(nil).IsHealthCheckRequired), nodeName)
}

// SignalDone mocks base method.
func (m *MockDependencyManager) SignalDone(nodeName string, phase types.WaitForPhase) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SignalDone", nodeName, phase)
}

// SignalDone indicates an expected call of SignalDone.
func (mr *MockDependencyManagerMockRecorder) SignalDone(nodeName, phase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalDone", reflect.TypeOf((*MockDependencyManager)(nil).SignalDone), nodeName, phase)
}

// String mocks base method.
func (m *MockDependencyManager) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockDependencyManagerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockDependencyManager)(nil).String))
}

// WaitForNodeDependencies mocks base method.
func (m *MockDependencyManager) WaitForNodeDependencies(nodeName string, phase types.WaitForPhase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForNodeDependencies", nodeName, phase)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForNodeDependencies indicates an expected call of WaitForNodeDependencies.
func (mr *MockDependencyManagerMockRecorder) WaitForNodeDependencies(nodeName, phase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForNodeDependencies", reflect.TypeOf((*MockDependencyManager)(nil).WaitForNodeDependencies), nodeName, phase)
}
